const { colors } = require('tailwindcss/defaultTheme');

module.exports = {
  plugins: [
    require('autoprefixer'),
    require('tailwindcss')({
      important: true,
      theme: {
        colors: {
          background: 'var(--bg)',
          btn: {
            'default': 'var(--bg-btn)',
            'hover': 'var(--bg-btn-hover)',
          },
          primary: {
            '050': 'var(--color-primary-050)',
            '100': 'var(--color-primary-100)',
            '200': 'var(--color-primary-200)',
            '300': 'var(--color-primary-300)',
            '400': 'var(--color-primary-400)',
            '500': 'var(--color-primary-500)',
            '600': 'var(--color-primary-600)',
            '700': 'var(--color-primary-700)',
            '800': 'var(--color-primary-800)',
            '900': 'var(--color-primary-900)',
          },
          danger: {
            '100': 'var(--color-danger-100)',
            '400': 'var(--color-danger-400)',
            '500': 'var(--color-danger-500)',
          },
          warning: {
            '100': 'var(--color-warning-100)',
            '400': 'var(--color-warning-400)',
            '500': 'var(--color-warning-500)',
          },
          notice: {
            '100': 'var(--color-notice-100)',
            '400': 'var(--color-notice-400)',
            '500': 'var(--color-notice-500)',
          },
          info: {
            '100': 'var(--color-info-100)',
            '400': 'var(--color-info-400)',
            '500': 'var(--color-info-500)',
          },
          gray: {
            '900': 'var(--color-gray-900)',
            '800': 'var(--color-gray-800)',
            '700': 'var(--color-gray-700)',
            '600': 'var(--color-gray-600)',
            '500': 'var(--color-gray-500)',
            '400': 'var(--color-gray-400)',
            '300': 'var(--color-gray-300)',
            '200': 'var(--color-gray-200)',
            '100': 'var(--color-gray-100)',
          },
        },
        textColor: {
          btn: {
            'default': 'var(--text-btn)',
            'hover': 'var(--text-btn-hover)',
          },
          gray: {
            '900': 'var(--color-gray-900)',
            '800': 'var(--color-gray-800)',
            '700': 'var(--color-gray-700)',
            '600': 'var(--color-gray-600)',
            '500': 'var(--color-gray-500)',
            '400': 'var(--color-gray-400)',
            '300': 'var(--color-gray-300)',
            '200': 'var(--color-gray-200)',
            '100': 'var(--color-gray-100)',
          },
          link: 'var(--text-link)',
          notice: 'var(--text-notice)',
          warning: 'var(--text-warning)',
          danger: 'var(--text-danger)',
          info: 'var(--text-info)',
          syntax1: 'var(--text-syntax-1)',
          syntax2: 'var(--text-syntax-2)',
          syntax3: 'var(--text-syntax-3)',
          syntax4: 'var(--text-syntax-4)',
        },
        opacity: {
          '0': '0',
          '10': '.1',
          '20': '.2',
          '30': '.3',
          '40': '.4',
          '50': '.5',
          '60': '.6',
          '70': '.7',
          '80': '.8',
          '90': '.9',
          '100': '1',
        },
      },
    }),
  ],
};
