version: "3"
services:
  web:
    command: 'reflex -s -r \.(go)$$ -d none go run github.com/gschier/schier.dev/cmd/web'
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - "8084:8084"
    restart: always
    environment:
      BASE_URL: http://localhost:8084
      CSRF_KEY: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      DEV_ENVIRONMENT: development
      DATABASE_URL: 'postgres://user:pass@postgres:5432/postgres?sslmode=disable'
      DO_SPACES_DOMAIN: nyc3.digitaloceanspaces.com
      MIGRATE_ON_START: enable
      DO_SPACES_SPACE: schierco
      PORT: "8084"
      STATIC_URL: /static
      STATIC_ROOT: ../frontend/static
    depends_on:
      - postgres
  postgres:
    ports:
      - "5438:5432"
    image: postgres:12
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~

