version: "3"
services:
  web:
    command: 'reflex -s -r \.(go|html)$$ -d none go run github.com/gschier/schier.dev/cmd/web'
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "8084:8084"
    restart: always
    environment:
      PORT: "8084"
      PRISMA_ENDPOINT: http://prisma:4488
      PRISMA_SECRET: development
      CSRF_KEY: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      STATIC_URL: /static
      BASE_URL: http://localhost:8084
      GA_ID: "" # UA-9837747-4
      CANONICAL_HOST: localhost
      DEV_ENVIRONMENT: development
      USER_PASSWORD: testing123
    depends_on:
      - prisma
      - postgres
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4488:4488"
    environment:
      PRISMA_CONFIG: |
        port: 4488
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  postgres:
    ports:
      - "5438:5432"
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
