[scripts.start]
help = "start backend and frontend"
combine = [ "frontend", "backend" ]

[scripts.frontend]
help = "start frontend watcher"
dir = "./frontend"
run = "npm start"

[scripts.backend]
help = "start dev server"
run = "docker-compose up"

[scripts.test]
root = true
help = "run tests"
dir = "./backend"
run = "go test ./... | grep -vE '(no test files)'"

[scripts.migrate]
root = true
help = "run database migrations"
run = "docker-compose run web manage migrate forward"
