[scripts.start]
root = true
help = "start backend and frontend"
combine = [ "frontend", "backend" ]

[scripts.down]
root = true
help = "shut down Docker"
run = "docker-compose down"

[scripts.production]
help = "start backend with production frontend builds"
combine = [ "backend" ]
run = "npm run build"
dir = "./frontend"

[scripts.frontend]
help = "start frontend watcher"
dir = "./frontend"
run = "npm start"

[scripts.build]
root = true
help = "build frontend"
dir = "./frontend"
run = "npm run build"

[scripts.backend]
help = "start dev server"
run = "docker-compose up web"

[scripts.test]
root = true
help = "run tests"
run = "go test ./... | grep -vE '(no test files)'"

[scripts.migrate]
root = true
help = "run database migrations"
run = "docker-compose run web manage migrate forward"
