name: Deploy

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DO_REGISTRY_TOKEN }}
          password: ${{ secrets.DO_REGISTRY_TOKEN }}
          repository: schierdev/schier.co
          registry: registry.digitalocean.com
          tags: ${{ github.sha }},latest
      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh && echo "${SSH_PRIVATE_KEY}" | tr -d '\r' > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
          ssh-keyscan nomad.schier.dev >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Render Job File
        run: cat ./deployment/job.tpl.hcl | sed "s|__GIT_SHA__|${GIT_SHA}|g" | cat > ./job.hcl
        env:
          GIT_SHA: ${{ github.sha }}
      - name: Deploy to Nomad
        run: |
          scp ./job.hcl root@nomad.schier.dev:/tmp/schierco.hcl
          ssh root@nomad.schier.dev nomad job run \
            -address="http://${NOMAD_IP_PRV}:4646" \
            -token="${NOMAD_TOKEN}" /tmp/schierco.hcl
        env:
          NOMAD_IP_PRV: ${{ secrets.NOMAD_IP_PRV }}
          NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
