name: Main

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker/build-push-action@v1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          username: ${{ secrets.DO_REGISTRY_TOKEN }}
          password: ${{ secrets.DO_REGISTRY_TOKEN }}
          repository: schierdev/schier.co
          registry: registry.digitalocean.com
          tag_with_sha: true
          tags: latest
