name: Main

on:
  push:
    branches:
      - master

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v2
      - name: Run Tests
        run: cd ./backend && go test ./...
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DO_REGISTRY_TOKEN }}
          password: ${{ secrets.DO_REGISTRY_TOKEN }}
          repository: schierdev
          registry: registry.digitalocean.com
          tag_with_sha: true
          tags: latest
